---
- name: edit webminfile
  hosts: all
  tasks:
   - name: add services
     lineinfile:
       state: present
       insertafter: EOF
       dest: /etc/sysctl.conf
       line: "{{ item }}"
     with_items:
        - net.ipv4.ip_forward = 0
        - kernel.sysrq = 0
        - kernel.core_uses_pid = 1
        - net.ipv4.tcp_syncookies = 1
        - kernel.msgmnb = 65536
        - kernel.msgmax = 65536
        - kernel.shmmax = 4294967295
        - kernel.shmall = 268435456
        - net.ipv4.tcp_syncookies = 1
        - net.ipv4.tcp_synack_retries = 2
        - kernel.exec-shield=1
        - kernel.randomize_va_space= 1
        - net.ipv4.conf.all.rp_filter= 1
        - net.ipv4.conf.lo.rp_filter= 1
        - net.ipv4.conf.eth0.rp_filter= 1
        - net.ipv4.conf.eth1.rp_filter= 1
        - net.ipv4.conf.default.rp_filter = 1


# Do not accept source routing
# # Disable IP source routing
        - net.ipv4.conf.all.accept_source_route=0
        - net.ipv4.conf.lo.accept_source_route=0
        - net.ipv4.conf.eth0.accept_source_route=0
        - net.ipv4.conf.eth1.accept_source_route=0
        - net.ipv4.conf.default.accept_source_route = 0
#
# #Disable ICMP Redirect Acceptance
        - net.ipv4.conf.all.accept_redirects=0
        - net.ipv4.conf.lo.accept_redirects=0
        - net.ipv4.conf.eth0.accept_redirects=0
        - net.ipv4.conf.eth1.accept_redirects=0
        - net.ipv4.conf.default.accept_redirects=0
#
# #Enable Log Spoofed Packets, Source Routed Packets, Redirects Packets
        - net.ipv4.conf.all.log_martians=1
        - net.ipv4.conf.lo.log_martians=1
        - net.ipv4.conf.eth0.log_martians=1
        - net.ipv4.conf.eth1.log_martians=1
#
# # Controls the System Request debugging functionality of the kernel
# #Disables the magic-sysrq key
        - kernel.sysrq=0
#
# #Enable ignoring broadcasts request
        - net.ipv4.icmp_echo_ignore_broadcasts=1
        - net.ipv4.icmp_ignore_bogus_error_messages=1
#
# #Increase the tcp_time_wait buckets pool size
        - net.ipv4.tcp_max_tw_buckets=1440000



