---
- name: edit webminfile
  hosts: all
  tasks:
   - name: add services
     lineinfile:
       state: present
       insertafter: EOF
       dest: /etc/hosts 
       line: "{{ item }}"
     with_items:
        - 115.108.33.7           Tata_DSL_FO
        - 115.108.42.134         Tata_DSL_FO2
        - 122.169.99.109         Airtel_DSL_FO2
        - 203.199.134.8          xn015.balasai.com       xn015
        - 203.199.134.5          xn015.balasai.com       xn015
        - 103.228.50.1           pnq01.balasai.com       pnq01
           
   - name: add services
     lineinfile:
       state: present
       insertafter: EOF
       dest: /etc/resolv.conf
       line: "{{ item }}"
     with_items:
        
        #For Softlayer servers: 
        - nameserver 10.0.80.11
        - nameserver 10.0.80.12
        - nameserver 203.199.134.8


        #For VSNL datacenter                  
        - nameserver 203.197.12.42
        - nameserver 202.54.10.2
        - nameserver 203.199.134.8


        #For TCL IDC (Depends upon the Private IP range)
        - nameserver 192.168.20.1
        - nameserver 192.168.20.5
        - nameserver 203.199.134.5

        #For TCL IDC (Depends upon the Private IP range)
        - nameserver 192.168.21.252
        - nameserver 203.199.134.5
        - nameserver 8.8.8.8
       

